### ISSUE TITLE
Dataset link is down

### ISSUE THREAD

**Issue by arjunsharma97** [imRishabhGupta/Indian-Sign-Language-Recognition#1]
Hi
The link to the dataset that you have provided in your readme seems to be down. Can you please update it?

**Comment by imRishabhGupta** [comment]
Thanks @arjunsharma97 for noticing. Give me a day, I will update the link.

**Comment by KAVIN-M** [comment]
Hi,
Dataset link is still down please look into it

**Comment by imRishabhGupta** [comment]
Apologies!
Here is the link - https://drive.google.com/open?id=1wgXtF6QHKBuXRx3qxuf-o6aOmN87t8G-
I have also updated it on readme. 
Actually, I had lost the dataset from my local machine so I had to get it from my friend and thats why it took some time. Again sorry for the delay!

**Comment by KAVIN-M** [comment]
Thank you...
